repos:
  - repo: https://github.com/talos-systems/conform
    rev: v0.1.0-alpha.20
    hooks:
      - id: conform
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: detect-aws-credentials
      - id: detect-private-key
        exclude: dist/index.js
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id: detect-secrets
        exclude: dist/index.js
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.8.7
    hooks:
      - id: gitleaks
